### ISSUE TITLE
launching processes edited via Fluo and saved as Ruby fails

### ISSUE THREAD

**Issue by jmettraux** [kennethkalmer/ruote-kit#31]
```
cannot read process definition...
```

**Comment by jmettraux** [comment]
```
#<Ruote::Reader::Error: cannot read process definition>
#<Racc::ParseError: 
parse error on value ":" (tCOLON)>
/opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/racc/parser.rb:351:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/home/jmettraux/.gem/ruby/1.9.3/gems/ruby_parser-2.3.1/lib/ruby_parser_extras.rb:750:in `process'
/home/jmettraux/.gem/ruby/1.9.3/gems/rufus-treechecker-1.0.8/lib/rufus/treechecker.rb:552:in `parse'
/home/jmettraux/.gem/ruby/1.9.3/gems/rufus-treechecker-1.0.8/lib/rufus/treechecker.rb:545:in `parse'
/home/jmettraux/.gem/ruby/1.9.3/gems/rufus-treechecker-1.0.8/lib/rufus/treechecker.rb:168:in `check'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/svc/treechecker.rb:122:in `definition_check'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/reader/ruby_dsl.rb:181:in `read'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/reader.rb:111:in `block in read'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/reader.rb:103:in `each'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/reader.rb:103:in `read'
/home/jmettraux/.gem/ruby/1.9.3/bundler/gems/ruote-b7700f8718b5/lib/ruote/receiver/base.rb:205:in `launch'
/home/jmettraux/w/ruote-kit/lib/ruote-kit/resources/processes.rb:66:in `block in <class:Application>'
```

the ruby_parser used is just 1.9 "key: value" averse.
